---
sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
script:
- bundle exec rspec spec
jdk: oraclejdk8
before_install:
- git clone -b feature/event_interface https://github.com/elastic/logstash
